import Head from "next/head";
import { useRecoilState, useRecoilValue, atom, selector } from "recoil";
import styles from "@/styles/Home.module.css";

const textState = atom({
  key: "textState",
  default: "",
});

const charCountState = selector({
  key: "charCountState",
  get: ({ get }) => {
    const text = get(textState);
    return text.length;
  },
});

export default function Home() {
  const [text, setText] = useRecoilState(textState);

  const onChange = (event) => {
    setText(event.target.value);
  };

  const count = useRecoilValue(charCountState);

  return (
    <>
      <Head>
        <title>Counter App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Character Counter</h1>

        <div className={styles.container}>
          <input
            className={styles.input}
            type="text"
            value={text}
            onChange={onChange}
          />
        </div>
        <br />
        <div className={styles.echo}>Echo: {text}</div>

        <div className={styles.count}>Character count: {count}</div>
      </main>
    </>
  );
}
